INSERT INTO USER_ACCOUNT VALUES(1, 'APPROVER1', 'password1', true);
INSERT INTO USER_ACCOUNT VALUES(2, 'APPROVER2', 'password2', false);
INSERT INTO USER_ACCOUNT VALUES(3, 'APPROVER3', 'password3', true);